/**
 * Enterprise Skill Dataset (200+ skills)
 */

interface SkillDefinition {
  canonical: string;
  aliases: string[];
}

const SKILL_DATASET: SkillDefinition[] = [
  // Frontend (40)
  { canonical: "React", aliases: ["react.js", "reactjs", "react js"] },
  { canonical: "Vue.js", aliases: ["vue", "vuejs", "vue.js"] },
  { canonical: "Angular", aliases: ["angular.js", "angularjs"] },
  { canonical: "Next.js", aliases: ["nextjs", "next js"] },
  { canonical: "TypeScript", aliases: ["ts"] },
  { canonical: "JavaScript", aliases: ["js", "es6", "esnext"] },
  { canonical: "Tailwind CSS", aliases: ["tailwind", "tailwindcss"] },
  { canonical: "Redux", aliases: ["redux-thunk", "redux-saga", "rtk"] },
  { canonical: "Svelte", aliases: ["sveltejs"] },
  { canonical: "Webpack", aliases: ["webpack.js"] },
  { canonical: "Vite", aliases: [] },
  { canonical: "Three.js", aliases: ["threejs"] },
  { canonical: "HTML5", aliases: ["html"] },
  { canonical: "CSS3", aliases: ["css", "scss", "sass", "less"] },
  { canonical: "GraphQL", aliases: ["apollo", "relay"] },
  { canonical: "React Native", aliases: [] },
  { canonical: "Flutter", aliases: [] },
  { canonical: "SwiftUI", aliases: [] },
  { canonical: "PWA", aliases: ["progressive web app"] },
  { canonical: "Web Performance", aliases: ["lighthouse", "core web vitals"] },
  { canonical: "Accessibility", aliases: ["a11y", "wcag"] },
  { canonical: "Storybook", aliases: [] },
  { canonical: "Cypress", aliases: ["e2e testing"] },
  { canonical: "Playwright", aliases: [] },
  { canonical: "Jest", aliases: ["unit testing"] },
  { canonical: "React Query", aliases: ["tanstack query"] },
  { canonical: "Zustand", aliases: [] },
  { canonical: "Recoil", aliases: [] },
  { canonical: "MobX", aliases: [] },
  { canonical: "Styled Components", aliases: ["emotion"] },
  { canonical: "Material UI", aliases: ["mui"] },
  { canonical: "Chakra UI", aliases: [] },
  { canonical: "Framer Motion", aliases: [] },
  { canonical: "D3.js", aliases: [] },
  { canonical: "WebAssembly", aliases: ["wasm"] },
  { canonical: "Babel", aliases: [] },
  { canonical: "ESLint", aliases: [] },
  { canonical: "Prettier", aliases: [] },
  { canonical: "NPM", aliases: ["yarn", "pnpm"] },

  // Backend (40)
  { canonical: "Node.js", aliases: ["nodejs", "node js", "node.js"] },
  { canonical: "Express", aliases: ["express.js", "expressjs"] },
  { canonical: "Python", aliases: ["py"] },
  { canonical: "Django", aliases: ["drf"] },
  { canonical: "Flask", aliases: [] },
  { canonical: "FastAPI", aliases: [] },
  { canonical: "Go", aliases: ["golang"] },
  { canonical: "Rust", aliases: [] },
  { canonical: "Java", aliases: [] },
  { canonical: "Spring Boot", aliases: ["spring framework", "spring"] },
  { canonical: "Ruby on Rails", aliases: ["rails", "ruby"] },
  { canonical: "PHP", aliases: ["laravel", "symfony"] },
  { canonical: "C#", aliases: ["csharp", ".net", "dotnet"] },
  { canonical: "C++", aliases: ["cpp"] },
  { canonical: "Scala", aliases: [] },
  { canonical: "Kotlin", aliases: [] },
  { canonical: "Elixir", aliases: ["phoenix"] },
  { canonical: "Microservices", aliases: ["distributed systems"] },
  { canonical: "REST API", aliases: ["restful", "apis"] },
  { canonical: "gRPC", aliases: [] },
  { canonical: "WebSockets", aliases: ["socket.io"] },
  { canonical: "Serverless", aliases: ["lambda functions", "faas"] },
  { canonical: "API Gateway", aliases: [] },
  { canonical: "Kafka", aliases: ["confluent"] },
  { canonical: "RabbitMQ", aliases: [] },
  { canonical: "OAuth2", aliases: ["oidc", "auth0"] },
  { canonical: "JWT", aliases: [] },
  { canonical: "Prisma", aliases: ["orm"] },
  { canonical: "TypeORM", aliases: [] },
  { canonical: "Sequelize", aliases: [] },
  { canonical: "Mongoose", aliases: [] },
  { canonical: "Swagger", aliases: ["openapi"] },
  { canonical: "Apollo Server", aliases: [] },
  { canonical: "Fastify", aliases: [] },
  { canonical: "NestJS", aliases: [] },
  { canonical: "Koa", aliases: [] },
  { canonical: "ASP.NET Core", aliases: [] },
  { canonical: "Hibernate", aliases: [] },

  // Databases (20)
  { canonical: "PostgreSQL", aliases: ["postgres", "postgresql"] },
  { canonical: "MongoDB", aliases: ["mongo"] },
  { canonical: "MySQL", aliases: ["mysql"] },
  { canonical: "Redis", aliases: [] },
  { canonical: "Elasticsearch", aliases: ["elk", "kibana"] },
  { canonical: "DynamoDB", aliases: [] },
  { canonical: "Firebase", aliases: ["firestore"] },
  { canonical: "Supabase", aliases: [] },
  { canonical: "SQLite", aliases: [] },
  { canonical: "Cassandra", aliases: [] },
  { canonical: "MariaDB", aliases: [] },
  { canonical: "Oracle Database", aliases: [] },
  { canonical: "SQL Server", aliases: ["mssql"] },
  { canonical: "Neo4j", aliases: ["graph database"] },
  { canonical: "ClickHouse", aliases: [] },
  { canonical: "Snowflake", aliases: [] },
  { canonical: "Redshift", aliases: [] },
  { canonical: "BigQuery", aliases: [] },
  { canonical: "CockroachDB", aliases: [] },
  { canonical: "InfluxDB", aliases: [] },

  // Cloud & DevOps (40)
  { canonical: "Docker", aliases: ["containers"] },
  { canonical: "Kubernetes", aliases: ["k8s", "helm"] },
  { canonical: "Terraform", aliases: ["iac", "hcl"] },
  { canonical: "Ansible", aliases: [] },
  { canonical: "AWS", aliases: ["amazon web services", "ec2", "s3", "lambda", "rds"] },
  { canonical: "Azure", aliases: ["microsoft azure"] },
  { canonical: "GCP", aliases: ["google cloud platform", "google cloud", "gke"] },
  { canonical: "Jenkins", aliases: [] },
  { canonical: "GitHub Actions", aliases: ["github actions"] },
  { canonical: "CI/CD", aliases: ["continuous integration", "continuous deployment", "pipelines"] },
  { canonical: "Prometheus", aliases: [] },
  { canonical: "Grafana", aliases: [] },
  { canonical: "Linux", aliases: ["ubuntu", "debian", "centos", "rhel", "bash", "shell"] },
  { canonical: "CloudFormation", aliases: [] },
  { canonical: "Pulumi", aliases: [] },
  { canonical: "Chef", aliases: [] },
  { canonical: "Puppet", aliases: [] },
  { canonical: "GitLab CI", aliases: [] },
  { canonical: "CircleCI", aliases: [] },
  { canonical: "Bitbucket Pipelines", aliases: [] },
  { canonical: "ArgoCD", aliases: [] },
  { canonical: "Istio", aliases: ["service mesh"] },
  { canonical: "Nginx", aliases: [] },
  { canonical: "HAProxy", aliases: [] },
  { canonical: "CloudWatch", aliases: [] },
  { canonical: "Datadog", aliases: [] },
  { canonical: "New Relic", aliases: [] },
  { canonical: "Sentry", aliases: [] },
  { canonical: "Splunk", aliases: [] },
  { canonical: "CloudFront", aliases: ["cdn"] },
  { canonical: "VPC", aliases: ["networking"] },
  { canonical: "Route53", aliases: ["dns"] },
  { canonical: "IAM", aliases: [] },
  { canonical: "EKS", aliases: [] },
  { canonical: "ECS", aliases: [] },

  // Cybersecurity (30)
  { canonical: "SIEM", aliases: ["security information and event management"] },
  { canonical: "Wireshark", aliases: ["packet analysis"] },
  { canonical: "Nmap", aliases: [] },
  { canonical: "Metasploit", aliases: [] },
  { canonical: "Burp Suite", aliases: ["burpsuite"] },
  { canonical: "Penetration Testing", aliases: ["pentesting", "pentest", "pen-testing"] },
  { canonical: "Vulnerability Assessment", aliases: ["vulnerability scanning"] },
  { canonical: "Incident Response", aliases: ["ir", "csirt"] },
  { canonical: "EDR", aliases: ["endpoint detection and response"] },
  { canonical: "Threat Hunting", aliases: [] },
  { canonical: "CrowdStrike", aliases: [] },
  { canonical: "SentinelOne", aliases: [] },
  { canonical: "Firewalls", aliases: ["palo alto", "fortinet", "checkpoint"] },
  { canonical: "IDS/IPS", aliases: ["intrusion detection", "intrusion prevention", "snort", "suricata"] },
  { canonical: "Kali Linux", aliases: ["kali"] },
  { canonical: "OWASP", aliases: ["zap", "top 10"] },
  { canonical: "Cryptography", aliases: ["encryption", "tls", "pki"] },
  { canonical: "Identity Management", aliases: ["okta", "active directory"] },
  { canonical: "Endpoint Security", aliases: [] },
  { canonical: "Application Security", aliases: ["appsec"] },
  { canonical: "Network Security", aliases: [] },
  { canonical: "Cloud Security", aliases: ["cspm"] },
  { canonical: "Forensics", aliases: ["digital forensics"] },
  { canonical: "Malware Analysis", aliases: [] },
  { canonical: "NIST", aliases: [] },
  { canonical: "ISO 27001", aliases: [] },
  { canonical: "SOC", aliases: ["security operations center"] },

  // AI/ML & Data (30)
  { canonical: "Machine Learning", aliases: ["ml"] },
  { canonical: "Deep Learning", aliases: ["dl"] },
  { canonical: "Artificial Intelligence", aliases: ["ai"] },
  { canonical: "NLP", aliases: ["natural language processing"] },
  { canonical: "Computer Vision", aliases: ["cv", "opencv"] },
  { canonical: "PyTorch", aliases: [] },
  { canonical: "TensorFlow", aliases: ["tf", "keras"] },
  { canonical: "Scikit-learn", aliases: ["sklearn"] },
  { canonical: "Pandas", aliases: [] },
  { canonical: "NumPy", aliases: [] },
  { canonical: "LLM", aliases: ["large language models", "gpt", "transformers", "bert"] },
  { canonical: "LangChain", aliases: [] },
  { canonical: "HuggingFace", aliases: [] },
  { canonical: "Data Visualization", aliases: ["tableau", "power bi", "powerbi"] },
  { canonical: "Data Engineering", aliases: ["etl", "data pipelines"] },
  { canonical: "Apache Spark", aliases: ["pyspark", "spark"] },
  { canonical: "Hadoop", aliases: [] },
  { canonical: "Airflow", aliases: [] },
  { canonical: "MLOps", aliases: ["model deployment"] },
  { canonical: "Reinforcement Learning", aliases: [] },
  { canonical: "Statistics", aliases: [] },
  { canonical: "Data Mining", aliases: [] },
  { canonical: "Big Data", aliases: [] },
  { canonical: "Matplotlib", aliases: ["seaborn"] },

  // Others (Project Management / Mobile / Tools) (20)
  { canonical: "Git", aliases: ["github", "gitlab", "bitbucket", "version control"] },
  { canonical: "Agile", aliases: ["scrum", "kanban"] },
  { canonical: "Jira", aliases: ["atlassian"] },
  { canonical: "Confluence", aliases: [] },
  { canonical: "Project Management", aliases: ["pmp"] },
  { canonical: "SDLC", aliases: [] },
  { canonical: "Product Management", aliases: [] },
  { canonical: "UI/UX Design", aliases: ["figma", "sketch", "adobe xd"] },
  { canonical: "Wireframing", "aliases": [] },
  { canonical: "Prototyping", "aliases": [] },
  { canonical: "iOS", aliases: ["swift", "objective-c"] },
  { canonical: "Android", aliases: ["kotlin", "java mobile"] },
  { canonical: "Unity", aliases: ["game dev", "c# gaming"] },
  { canonical: "System Design", aliases: ["software architecture"] },
  { canonical: "TDD", aliases: ["test driven development"] },
];

export function extractSkills(text: string): string[] {
  const foundSkills = new Set<string>();
  const lowerText = text.toLowerCase();

  SKILL_DATASET.forEach(skill => {
    const patterns = [skill.canonical.toLowerCase(), ...skill.aliases.map(a => a.toLowerCase())];

    for (const pattern of patterns) {
      const escaped = pattern.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const regex = new RegExp(`(?<![a-zA-Z])${escaped}(?![a-zA-Z])`, "i");

      if (regex.test(lowerText)) {
        foundSkills.add(skill.canonical);
        break;
      }
    }
  });

  return Array.from(foundSkills);
}
